server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

## mustache ??(??? ?? ???? ?????? ??)
#  mvc:
#    view:
#      prefix: /templates/
#      suffix: .mustache

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      format-sql: true
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 942963499628-huunbf8jnct8sd5g6hvcfs6ukcfmu0ce.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile