server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

  ## mustache ??(??? ?? ???? ?????? ??)
  #  mvc:
  #    view:
  #      prefix: /templates/
  #      suffix: .mustache

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      format-sql: true
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 942963499628-huunbf8jnct8sd5g6hvcfs6ukcfmu0ce.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          facebook:
            client-id: 1719567395108497
            client-secret: 571af0b75f4b038998901a855bf8a846
            scope:
              - email
              - public_profile

          naver:
            client-id: LncjaQUro8TMJm_GsAdv
            client-secret: Yu2LJR_CNT
            scope:
              - name
              - email
            #- profile_image
            client-name: Naver
            authorization-grant-type: authorization_code                  # oauth2의 동작 방식은 여러가지가 있는데, 코드를 응답받는 방식으로 진행한다는 의미
            redirect-uri: http://localhost:8080/login/oauth2/code/naver   # naver의 경우 redirect-uri를 설정해줘야함. (google, facebook의 경우 디폴트로 설정되어 있음)

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response                               #회원정보를 json으로 받는데 response라는 키 값으로 네이버가 리턴해줄 것이다.

