server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

## mustache ??(??? ?? ???? ?????? ??)
#  mvc:
#    view:
#      prefix: /templates/
#      suffix: .mustache

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      format-sql: true
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: test
            client-secret: test
            scope:
            - email
            - profile
          facebook:
            client-id: tset
            client-secret: test
            scope:
            - email
            - public_profile
